'------------------------------------------------------------------------------
' <auto-generated>
'	 This code was generated by a tool.
'	 Runtime Version:4.0.30319.34003
'
'	 Changes to this file may cause incorrect behavior and will be lost if
'	 the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
	
	'This class was auto-generated by the StronglyTypedResourceBuilder
	'class via a tool like ResGen or Visual Studio.
	'To add or remove a member, edit your .ResX file then rerun ResGen
	'with the /str option, or rebuild your VS project.
	'''<summary>
	'''  A strongly-typed resource class, for looking up localized strings, etc.
	'''</summary>
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
	 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
	 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
	 Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
	Friend Module Resources
		
		Private resourceMan As Global.System.Resources.ResourceManager
		
		Private resourceCulture As Global.System.Globalization.CultureInfo
		
		'''<summary>
		'''  Returns the cached ResourceManager instance used by this class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.BoundData.Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property
		
		'''<summary>
		'''  Overrides the current thread's CurrentUICulture property for all
		'''  resource lookups using this strongly typed resource class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property
		
		Friend ReadOnly Property ConnectionString() As String
			Get
				Return ResourceManager.GetString("ConnectionString", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property CSVDataSetPathComma() As String
			Get
				Return ResourceManager.GetString("CSVDataSetPathComma", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property CSVDataSetPathHeaderTab() As String
			Get
				Return ResourceManager.GetString("CSVDataSetPathHeaderTab", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property CSVDataSetPathHeaderFixed() As String
			Get
				Return ResourceManager.GetString("CSVDataSetPathHeaderFixed", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property CSVDataSetPathFixed() As String
			Get
				Return ResourceManager.GetString("CSVDataSetPathFixed", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property CSVEncoding() As String
			Get
				Return ResourceManager.GetString("CSVEncoding", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property ReportName() As String
			Get
				Return ResourceManager.GetString("ReportName", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property SQLServerProblem() As String
			Get
				Return ResourceManager.GetString("SQLServerProblem", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property SelectCompanyName() As String
			Get
				Return ResourceManager.GetString("SelectCompanyName", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property SelectSQLServer() As String
			Get
				Return ResourceManager.GetString("SelectSQLServer", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property SaveDataAs() As String
			Get
				Return ResourceManager.GetString("SaveDataAs", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property Filter() As String
			Get
				Return ResourceManager.GetString("Filter", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property OpenDataFile() As String
			Get
				Return ResourceManager.GetString("OpenDataFile", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property NoHeaderFixed() As String
			Get
				Return ResourceManager.GetString("NoHeaderFixed", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property HeaderExistsFixed() As String
			Get
				Return ResourceManager.GetString("HeaderExistsFixed", resourceCulture)
			End Get
		End Property

	End Module
End Namespace
