//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapeCity.ActiveReports.Samples.Charting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.Charting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        internal static string Clockwise {
            get {
                return ResourceManager.GetString("Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\Data\NWIND.MDB;Persist Security Info=False.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterclockwise.
        /// </summary>
        internal static string Counterclockwise {
            get {
                return ResourceManager.GetString("Counterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction of rotation:.
        /// </summary>
        internal static string DirectionOfRotation {
            get {
                return ResourceManager.GetString("DirectionOfRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance chart.
        /// </summary>
        internal static string FinanceChart {
            get {
                return ResourceManager.GetString("FinanceChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rpt2DBar.rpx.
        /// </summary>
        internal static string rpt2DBar {
            get {
                return ResourceManager.GetString("rpt2DBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rpt3DBar.rpx.
        /// </summary>
        internal static string rpt3DBar {
            get {
                return ResourceManager.GetString("rpt3DBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rpt3DPie.rpx.
        /// </summary>
        internal static string rpt3DPie {
            get {
                return ResourceManager.GetString("rpt3DPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptCandle.rpx.
        /// </summary>
        internal static string rptCandle {
            get {
                return ResourceManager.GetString("rptCandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptStackedArea.rpx.
        /// </summary>
        internal static string rptStackedArea {
            get {
                return ResourceManager.GetString("rptStackedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked area chart.
        /// </summary>
        internal static string StackedAreaChart {
            get {
                return ResourceManager.GetString("StackedAreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D bar chart.
        /// </summary>
        internal static string ThreeDBarChart {
            get {
                return ResourceManager.GetString("ThreeDBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D pie chart.
        /// </summary>
        internal static string ThreeDPieChart {
            get {
                return ResourceManager.GetString("ThreeDPieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D bar chart.
        /// </summary>
        internal static string TwoDBarChart {
            get {
                return ResourceManager.GetString("TwoDBarChart", resourceCulture);
            }
        }
    }
}
