'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.SubReport.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\Data\Nwind.mdb;Persist Security Info=False.
        '''</summary>
        Friend ReadOnly Property ConnectionString() As String
            Get
                Return ResourceManager.GetString("ConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a Sample Report from DropDown List.
        '''</summary>
        Friend ReadOnly Property ItemText1() As String
            Get
                Return ResourceManager.GetString("ItemText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Simple SubReport.
        '''</summary>
        Friend ReadOnly Property ItemText2() As String
            Get
                Return ResourceManager.GetString("ItemText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nested SubReport.
        '''</summary>
        Friend ReadOnly Property ItemText3() As String
            Get
                Return ResourceManager.GetString("ItemText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hierarchical SubReport.
        '''</summary>
        Friend ReadOnly Property ItemText4() As String
            Get
                Return ResourceManager.GetString("ItemText4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SubReport using the data set that contains relationship.
        '''</summary>
        Friend ReadOnly Property ItemText5() As String
            Get
                Return ResourceManager.GetString("ItemText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Master-detail report containing a SubReport.
        '''</summary>
        Friend ReadOnly Property ItemText6() As String
            Get
                Return ResourceManager.GetString("ItemText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bookmark in SubReport.
        '''</summary>
        Friend ReadOnly Property ItemText7() As String
            Get
                Return ResourceManager.GetString("ItemText7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use a parameter in the SubReport.
        '''</summary>
        Friend ReadOnly Property ItemText8() As String
            Get
                Return ResourceManager.GetString("ItemText8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To view the DataSet with multiple tables using SubReports.
        '''</summary>
        Friend ReadOnly Property ItemText9() As String
            Get
                Return ResourceManager.GetString("ItemText9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptBookmarkMain.rpx.
        '''</summary>
        Friend ReadOnly Property rptBookmarkMain() As String
            Get
                Return ResourceManager.GetString("rptBookmarkMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptBookmarkSub.rpx.
        '''</summary>
        Friend ReadOnly Property rptBookmarkSub() As String
            Get
                Return ResourceManager.GetString("rptBookmarkSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptDSRelationChildMain.rpx.
        '''</summary>
        Friend ReadOnly Property rptDSRelationChildMain() As String
            Get
                Return ResourceManager.GetString("rptDSRelationChildMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptDSRelationChildSub.rpx.
        '''</summary>
        Friend ReadOnly Property rptDSRelationChildSub() As String
            Get
                Return ResourceManager.GetString("rptDSRelationChildSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptDSRelationParent.rpx.
        '''</summary>
        Friend ReadOnly Property rptDSRelationParent() As String
            Get
                Return ResourceManager.GetString("rptDSRelationParent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptHierarchicalMain.rpx.
        '''</summary>
        Friend ReadOnly Property rptHierarchicalMain() As String
            Get
                Return ResourceManager.GetString("rptHierarchicalMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptHierarchicalSub.rpx.
        '''</summary>
        Friend ReadOnly Property rptHierarchicalSub() As String
            Get
                Return ResourceManager.GetString("rptHierarchicalSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptMasterMain.rpx.
        '''</summary>
        Friend ReadOnly Property rptMasterMain() As String
            Get
                Return ResourceManager.GetString("rptMasterMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptMasterSub.rpx.
        '''</summary>
        Friend ReadOnly Property rptMasterSub() As String
            Get
                Return ResourceManager.GetString("rptMasterSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptNestedChildMain.rpx.
        '''</summary>
        Friend ReadOnly Property rptNestedChildMain() As String
            Get
                Return ResourceManager.GetString("rptNestedChildMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptNestedChildSub.rpx.
        '''</summary>
        Friend ReadOnly Property rptNestedChildSub() As String
            Get
                Return ResourceManager.GetString("rptNestedChildSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptNestedParent.rpx.
        '''</summary>
        Friend ReadOnly Property rptNestedParent() As String
            Get
                Return ResourceManager.GetString("rptNestedParent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptParamMain.rpx.
        '''</summary>
        Friend ReadOnly Property rptParamMain() As String
            Get
                Return ResourceManager.GetString("rptParamMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptParamSub.rpx.
        '''</summary>
        Friend ReadOnly Property rptParamSub() As String
            Get
                Return ResourceManager.GetString("rptParamSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptSimpleMain.rpx.
        '''</summary>
        Friend ReadOnly Property rptSimpleMain() As String
            Get
                Return ResourceManager.GetString("rptSimpleMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptSimpleSub.rpx.
        '''</summary>
        Friend ReadOnly Property rptSimpleSub() As String
            Get
                Return ResourceManager.GetString("rptSimpleSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptUnboundDSMain.rpx.
        '''</summary>
        Friend ReadOnly Property rptUnboundDSMain() As String
            Get
                Return ResourceManager.GetString("rptUnboundDSMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\rptUnboundDSSub.rpx.
        '''</summary>
        Friend ReadOnly Property rptUnboundDSSub() As String
            Get
                Return ResourceManager.GetString("rptUnboundDSSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider=MSDataShape;Data Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\Data\Nwind.mdb;Persist Security Info=False.
        '''</summary>
        Friend ReadOnly Property ShapeDataConnectionString() As String
            Get
                Return ResourceManager.GetString("ShapeDataConnectionString", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
