'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GrapeCity.ActiveReports.Designer.Win.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;About.
        '''</summary>
        Friend ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property App() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("App", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CmdExport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdExport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CmdNewReport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdNewReport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CmdOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CmdSave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdSave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CmdSaveAs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdSaveAs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Selection: .
        '''</summary>
        Friend ReadOnly Property CurrentSelection() As String
            Get
                Return ResourceManager.GetString("CurrentSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ActiveReports 13.
        '''</summary>
        Friend ReadOnly Property DefaultGroup() As String
            Get
                Return ResourceManager.GetString("DefaultGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Untitled.rdlx.
        '''</summary>
        Friend ReadOnly Property DefaultReportNameRdl() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRdl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Untitled.rdlx.
        '''</summary>
        Friend ReadOnly Property DefaultReportNameRdlx() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRdlx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Untitled.rdlx-master.
        '''</summary>
        Friend ReadOnly Property DefaultReportNameRdlxMaster() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRdlxMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Untitled.rpx.
        '''</summary>
        Friend ReadOnly Property DefaultReportNameRpx() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRpx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DesignerForm.
        '''</summary>
        Friend ReadOnly Property DesignerFormName() As String
            Get
                Return ResourceManager.GetString("DesignerFormName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GrapeCity ActiveReports Report Designer.
        '''</summary>
        Friend ReadOnly Property DesignerFormTitle() As String
            Get
                Return ResourceManager.GetString("DesignerFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *.
        '''</summary>
        Friend ReadOnly Property DirtySign() As String
            Get
                Return ResourceManager.GetString("DirtySign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes to &apos;{0}&apos;?.
        '''</summary>
        Friend ReadOnly Property EudUnsavedChangesMessage() As String
            Get
                Return ResourceManager.GetString("EudUnsavedChangesMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsaved Changes.
        '''</summary>
        Friend ReadOnly Property EudUnsavedChangesTitle() As String
            Get
                Return ResourceManager.GetString("EudUnsavedChangesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;xit.
        '''</summary>
        Friend ReadOnly Property ExitText() As String
            Get
                Return ResourceManager.GetString("ExitText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Export.
        '''</summary>
        Friend ReadOnly Property Export() As String
            Get
                Return ResourceManager.GetString("Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Export.
        '''</summary>
        Friend ReadOnly Property ExportText() As String
            Get
                Return ResourceManager.GetString("ExportText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GroupEditorHide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupEditorHide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GroupEditorShow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupEditorShow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide Group Editor.
        '''</summary>
        Friend ReadOnly Property HideGroupPanelToolTip() As String
            Get
                Return ResourceManager.GetString("HideGroupPanelToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;New....
        '''</summary>
        Friend ReadOnly Property NewText() As String
            Get
                Return ResourceManager.GetString("NewText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend ReadOnly Property NewToolTip() As String
            Get
                Return ResourceManager.GetString("NewToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Selection.
        '''</summary>
        Friend ReadOnly Property NoSelection() As String
            Get
                Return ResourceManager.GetString("NoSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Open....
        '''</summary>
        Friend ReadOnly Property Open() As String
            Get
                Return ResourceManager.GetString("Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open As Library.
        '''</summary>
        Friend ReadOnly Property OpenAsLibrary() As String
            Get
                Return ResourceManager.GetString("OpenAsLibrary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend ReadOnly Property OpenToolTip() As String
            Get
                Return ResourceManager.GetString("OpenToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .rdl.
        '''</summary>
        Friend ReadOnly Property RdlExtension() As String
            Get
                Return ResourceManager.GetString("RdlExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .rdlx.
        '''</summary>
        Friend ReadOnly Property RdlxExtension() As String
            Get
                Return ResourceManager.GetString("RdlxExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .rdlx-master.
        '''</summary>
        Friend ReadOnly Property RdlxMasterExtension() As String
            Get
                Return ResourceManager.GetString("RdlxMasterExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File {0} is not valid report file..
        '''</summary>
        Friend ReadOnly Property ReportIsNotValid() As String
            Get
                Return ResourceManager.GetString("ReportIsNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .rpx.
        '''</summary>
        Friend ReadOnly Property RpxExtension() As String
            Get
                Return ResourceManager.GetString("RpxExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EndUserDesigner - .
        '''</summary>
        Friend ReadOnly Property SampleNameTitle() As String
            Get
                Return ResourceManager.GetString("SampleNameTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Save.
        '''</summary>
        Friend ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S&amp;ave as....
        '''</summary>
        Friend ReadOnly Property SaveAs() As String
            Get
                Return ResourceManager.GetString("SaveAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RDL Report Files (*.rdlx)|*.rdlx.
        '''</summary>
        Friend ReadOnly Property SaveRdlFilter() As String
            Get
                Return ResourceManager.GetString("SaveRdlFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Report Files (*.rdlx)|*.rdlx.
        '''</summary>
        Friend ReadOnly Property SaveRdlxFilter() As String
            Get
                Return ResourceManager.GetString("SaveRdlxFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RDL Report Master Files (*.rdlx-master)|*.rdlx-master.
        '''</summary>
        Friend ReadOnly Property SaveRdlxMasterFilter() As String
            Get
                Return ResourceManager.GetString("SaveRdlxMasterFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Section Report Files (*.rpx)|*.rpx.
        '''</summary>
        Friend ReadOnly Property SaveRpxFilter() As String
            Get
                Return ResourceManager.GetString("SaveRpxFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend ReadOnly Property SaveToolTip() As String
            Get
                Return ResourceManager.GetString("SaveToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Group Editor.
        '''</summary>
        Friend ReadOnly Property ShowGroupPanelToolTip() As String
            Get
                Return ResourceManager.GetString("ShowGroupPanelToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}{1} - {2}.
        '''</summary>
        Friend ReadOnly Property TitleFormat() As String
            Get
                Return ResourceManager.GetString("TitleFormat", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
