//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.34003
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapeCity.ActiveReports.Samples.BoundData.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.BoundData.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static string ConnectionString {
			get {
				return ResourceManager.GetString("ConnectionString", resourceCulture);
			}
		}
		internal static string CSVDataSetPathComma
		{
			get
			{
				return ResourceManager.GetString("CSVDataSetPathComma", resourceCulture);
			}
		}
		internal static string CSVDataSetPathHeaderTab
		{
			get
			{
				return ResourceManager.GetString("CSVDataSetPathHeaderTab", resourceCulture);
			}
		}
		internal static string CSVDataSetPathHeaderFixed
		{
			get
			{
				return ResourceManager.GetString("CSVDataSetPathHeaderFixed", resourceCulture);
			}
		}
		internal static string CSVDataSetPathFixed
		{
			get
			{
				return ResourceManager.GetString("CSVDataSetPathFixed", resourceCulture);
			}
		}
		internal static string CSVEncoding
		{
			get
			{
				return ResourceManager.GetString("CSVEncoding", resourceCulture);
			}
		}
		internal static string ReportName
		{
			get
			{
				return ResourceManager.GetString("ReportName", resourceCulture);
			}
		}
		internal static string SQLServerProblem
		{
			get
			{
				return ResourceManager.GetString("SQLServerProblem", resourceCulture);
			}
		}

		internal static string SelectCompanyName
		{
			get
			{
				return ResourceManager.GetString("SelectCompanyName", resourceCulture);
			}
		}

		internal static string SelectSQLServer
		{
			get
			{
				return ResourceManager.GetString("SelectSQLServer", resourceCulture);
			}
		}

		internal static string SaveDataAs
		{
			get
			{
				return ResourceManager.GetString("SaveDataAs", resourceCulture);
			}
		}

		internal static string Filter
		{
			get
			{
				return ResourceManager.GetString("Filter", resourceCulture);
			}
		}

		internal static string OpenDataFile
		{
			get
			{
				return ResourceManager.GetString("OpenDataFile", resourceCulture);
			}
		}

		internal static string NoHeaderFixed
		{
			get
			{
				return ResourceManager.GetString("NoHeaderFixed", resourceCulture);
			}
		}

		internal static string HeaderExistsFixed
		{
			get
			{
				return ResourceManager.GetString("HeaderExistsFixed", resourceCulture);
			}
		}
	}
}
