'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Generation date: 18.10.2018 13:39:16
Namespace ODataDataSource
	'''<summary>
	'''There are no comments for CustomerSingle in the schema.
	'''</summary>
	<Global.Microsoft.OData.Client.OriginalNameAttribute("CustomerSingle")>
	Partial Public Class CustomerSingle
		Inherits Global.Microsoft.OData.Client.DataServiceQuerySingle(Of Customer)
		''' <summary>
		''' Initialize a new CustomerSingle object.
		''' </summary>
		Public Sub New(ByVal context As Global.Microsoft.OData.Client.DataServiceContext, ByVal path As String)
			MyBase.New(context, path)
		End Sub

		''' <summary>
		''' Initialize a new CustomerSingle object.
		''' </summary>
		Public Sub New(ByVal context As Global.Microsoft.OData.Client.DataServiceContext, ByVal path As String, ByVal isComposable As Boolean)
			MyBase.New(context, path, isComposable)
		End Sub

		''' <summary>
		''' Initialize a new CustomerSingle object.
		''' </summary>
		Public Sub New(ByVal query As Global.Microsoft.OData.Client.DataServiceQuerySingle(Of Customer))
			MyBase.New(query)
		End Sub
	End Class
	'''<summary>
	'''There are no comments for Customer in the schema.
	'''</summary>
	'''<KeyProperties>
	'''CustomerID
	'''</KeyProperties>
	<Global.Microsoft.OData.Client.Key("CustomerID")>
	<Global.Microsoft.OData.Client.OriginalNameAttribute("Customer")>
	Partial Public Class Customer
		Inherits Global.Microsoft.OData.Client.BaseEntityType
		Implements Global.System.ComponentModel.INotifyPropertyChanged
		'''<summary>
		'''Create a new Customer object.
		'''</summary>
		'''<param name="customerID">Initial value of CustomerID.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Public Shared Function CreateCustomer(ByVal customerID As String) As Customer
			Dim customer As Customer = New Customer()
			customer.CustomerID = customerID
			Return customer
		End Function
		'''<summary>
		'''There are no comments for Property CustomerID in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("CustomerID")>
		Public Property CustomerID() As String
			Get
				Return Me._CustomerID
			End Get
			Set
				Me.OnCustomerIDChanging(Value)
				Me._CustomerID = Value
				Me.OnCustomerIDChanged()
				Me.OnPropertyChanged("CustomerID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _CustomerID As String
		Partial Private Sub OnCustomerIDChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCustomerIDChanged()
		End Sub
		'''<summary>
		'''There are no comments for Property CompanyName in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("CompanyName")>
		Public Property CompanyName() As String
			Get
				Return Me._CompanyName
			End Get
			Set
				Me.OnCompanyNameChanging(Value)
				Me._CompanyName = Value
				Me.OnCompanyNameChanged()
				Me.OnPropertyChanged("CompanyName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _CompanyName As String
		Partial Private Sub OnCompanyNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub
		'''<summary>
		'''There are no comments for Property ContactName in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("ContactName")>
		Public Property ContactName() As String
			Get
				Return Me._ContactName
			End Get
			Set
				Me.OnContactNameChanging(Value)
				Me._ContactName = Value
				Me.OnContactNameChanged()
				Me.OnPropertyChanged("ContactName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _ContactName As String
		Partial Private Sub OnContactNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnContactNameChanged()
		End Sub
		'''<summary>
		'''There are no comments for Property Address in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("Address")>
		Public Property Address() As String
			Get
				Return Me._Address
			End Get
			Set
				Me.OnAddressChanging(Value)
				Me._Address = Value
				Me.OnAddressChanged()
				Me.OnPropertyChanged("Address")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _Address As String
		Partial Private Sub OnAddressChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnAddressChanged()
		End Sub
		''' <summary>
		''' This event is raised when the value of the property is changed
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		''' <summary>
		''' The value of the property is changed
		''' </summary>
		''' <param name="property">property name</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Not (Me.PropertyChangedEvent) Is Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
	'''<summary>
	'''There are no comments for MovieSingle in the schema.
	'''</summary>
	<Global.Microsoft.OData.Client.OriginalNameAttribute("MovieSingle")>
	Partial Public Class MovieSingle
		Inherits Global.Microsoft.OData.Client.DataServiceQuerySingle(Of Movie)
		''' <summary>
		''' Initialize a new MovieSingle object.
		''' </summary>
		Public Sub New(ByVal context As Global.Microsoft.OData.Client.DataServiceContext, ByVal path As String)
			MyBase.New(context, path)
		End Sub

		''' <summary>
		''' Initialize a new MovieSingle object.
		''' </summary>
		Public Sub New(ByVal context As Global.Microsoft.OData.Client.DataServiceContext, ByVal path As String, ByVal isComposable As Boolean)
			MyBase.New(context, path, isComposable)
		End Sub

		''' <summary>
		''' Initialize a new MovieSingle object.
		''' </summary>
		Public Sub New(ByVal query As Global.Microsoft.OData.Client.DataServiceQuerySingle(Of Movie))
			MyBase.New(query)
		End Sub
	End Class
	'''<summary>
	'''There are no comments for Movie in the schema.
	'''</summary>
	'''<KeyProperties>
	'''ID
	'''</KeyProperties>
	<Global.Microsoft.OData.Client.Key("ID")>
	<Global.Microsoft.OData.Client.OriginalNameAttribute("Movie")>
	Partial Public Class Movie
		Inherits Global.Microsoft.OData.Client.BaseEntityType
		Implements Global.System.ComponentModel.INotifyPropertyChanged
		'''<summary>
		'''Create a new Movie object.
		'''</summary>
		'''<param name="ID">Initial value of ID.</param>
		'''<param name="yearReleased">Initial value of YearReleased.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Public Shared Function CreateMovie(ByVal ID As Integer, ByVal yearReleased As Integer) As Movie
			Dim movie As Movie = New Movie()
			movie.ID = ID
			movie.YearReleased = yearReleased
			Return movie
		End Function
		'''<summary>
		'''There are no comments for Property ID in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("ID")>
		Public Property ID() As Integer
			Get
				Return Me._ID
			End Get
			Set
				Me.OnIDChanging(Value)
				Me._ID = Value
				Me.OnIDChanged()
				Me.OnPropertyChanged("ID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _ID As Integer
		Partial Private Sub OnIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnIDChanged()
		End Sub
		'''<summary>
		'''There are no comments for Property Title in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("Title")>
		Public Property Title() As String
			Get
				Return Me._Title
			End Get
			Set
				Me.OnTitleChanging(Value)
				Me._Title = Value
				Me.OnTitleChanged()
				Me.OnPropertyChanged("Title")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _Title As String
		Partial Private Sub OnTitleChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnTitleChanged()
		End Sub
		'''<summary>
		'''There are no comments for Property MPAA in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("MPAA")>
		Public Property MPAA() As String
			Get
				Return Me._MPAA
			End Get
			Set
				Me.OnMPAAChanging(Value)
				Me._MPAA = Value
				Me.OnMPAAChanged()
				Me.OnPropertyChanged("MPAA")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _MPAA As String
		Partial Private Sub OnMPAAChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnMPAAChanged()
		End Sub
		'''<summary>
		'''There are no comments for Property YearReleased in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("YearReleased")>
		Public Property YearReleased() As Integer
			Get
				Return Me._YearReleased
			End Get
			Set
				Me.OnYearReleasedChanging(Value)
				Me._YearReleased = Value
				Me.OnYearReleasedChanged()
				Me.OnPropertyChanged("YearReleased")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _YearReleased As Integer
		Partial Private Sub OnYearReleasedChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnYearReleasedChanged()
		End Sub
		''' <summary>
		''' This event is raised when the value of the property is changed
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		''' <summary>
		''' The value of the property is changed
		''' </summary>
		''' <param name="property">property name</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Not (Me.PropertyChangedEvent) Is Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
	''' <summary>
	''' Class containing all extension methods
	''' </summary>
	Public Module ExtensionMethods
		''' <summary>
		''' Get an entity of type ODataDataSource.Customer as ODataDataSource.CustomerSingle specified by key from an entity set
		''' </summary>
		''' <param name="source">source entity set</param>
		''' <param name="keys">dictionary with the names and values of keys</param>
		<Global.System.Runtime.CompilerServices.Extension()>
		Public Function ByKey(ByVal source As Global.Microsoft.OData.Client.DataServiceQuery(Of ODataDataSource.Customer), ByVal keys As Global.System.Collections.Generic.Dictionary(Of String, Object)) As ODataDataSource.CustomerSingle
			Return New ODataDataSource.CustomerSingle(source.Context, source.GetKeyPath(Global.Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)))
		End Function
		''' <summary>
		''' Get an entity of type ODataDataSource.Customer as ODataDataSource.CustomerSingle specified by key from an entity set
		''' </summary>
		''' <param name="source">source entity set</param>
		''' <param name="customerID">The value of customerID</param>
		<Global.System.Runtime.CompilerServices.Extension()>
		Public Function ByKey(ByVal source As Global.Microsoft.OData.Client.DataServiceQuery(Of ODataDataSource.Customer),
			customerID As String) As ODataDataSource.CustomerSingle
			Dim keys As Global.System.Collections.Generic.Dictionary(Of String, Object) = New Global.System.Collections.Generic.Dictionary(Of String, Object)() From
			{
				{"CustomerID", customerID}
			}
			Return New ODataDataSource.CustomerSingle(source.Context, source.GetKeyPath(Global.Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)))
		End Function
		''' <summary>
		''' Get an entity of type ODataDataSource.Movie as ODataDataSource.MovieSingle specified by key from an entity set
		''' </summary>
		''' <param name="source">source entity set</param>
		''' <param name="keys">dictionary with the names and values of keys</param>
		<Global.System.Runtime.CompilerServices.Extension()>
		Public Function ByKey(ByVal source As Global.Microsoft.OData.Client.DataServiceQuery(Of ODataDataSource.Movie), ByVal keys As Global.System.Collections.Generic.Dictionary(Of String, Object)) As ODataDataSource.MovieSingle
			Return New ODataDataSource.MovieSingle(source.Context, source.GetKeyPath(Global.Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)))
		End Function
		''' <summary>
		''' Get an entity of type ODataDataSource.Movie as ODataDataSource.MovieSingle specified by key from an entity set
		''' </summary>
		''' <param name="source">source entity set</param>
		''' <param name="iD">The value of iD</param>
		<Global.System.Runtime.CompilerServices.Extension()>
		Public Function ByKey(ByVal source As Global.Microsoft.OData.Client.DataServiceQuery(Of ODataDataSource.Movie),
			iD As Integer) As ODataDataSource.MovieSingle
			Dim keys As Global.System.Collections.Generic.Dictionary(Of String, Object) = New Global.System.Collections.Generic.Dictionary(Of String, Object)() From
			{
				{"ID", iD}
			}
			Return New ODataDataSource.MovieSingle(source.Context, source.GetKeyPath(Global.Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)))
		End Function
	End Module
End Namespace
Namespace ODataDataSource.[Default]
	'''<summary>
	'''There are no comments for Container in the schema.
	'''</summary>
	<Global.Microsoft.OData.Client.OriginalNameAttribute("Container")>
	Partial Public Class Container
		Inherits Global.Microsoft.OData.Client.DataServiceContext
		'''<summary>
		'''Initialize a new Container object.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Public Sub New(ByVal serviceRoot As Global.System.Uri)
			MyBase.New(serviceRoot, Global.Microsoft.OData.Client.ODataProtocolVersion.V4)
			Me.ResolveName = AddressOf Me.ResolveNameFromType
			Me.ResolveType = AddressOf Me.ResolveTypeFromName
			Me.OnContextCreated()
			Me.Format.LoadServiceModel = AddressOf GeneratedEdmModel.GetInstance
			Me.Format.UseJson()
		End Sub
		Partial Private Sub OnContextCreated()
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private Shared ROOTNAMESPACE As String = GetType(Container).Namespace.Remove(GetType(Container).Namespace.LastIndexOf("ODataDataSource.Default"))
		'''<summary>
		'''Since the namespace configured for this service reference
		'''in Visual Studio is different from the one indicated in the
		'''server schema, use type-mappers to map between the two.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
			Dim resolvedType As Global.System.Type = Me.DefaultResolveType(typeName, "ODataDataSource", String.Concat(ROOTNAMESPACE, "ODataDataSource"))
			If (Not (resolvedType) Is Nothing) Then
				Return resolvedType
			End If
			resolvedType = Me.DefaultResolveType(typeName, "Default", String.Concat(ROOTNAMESPACE, "ODataDataSource.Default"))
			If (Not (resolvedType) Is Nothing) Then
				Return resolvedType
			End If
			Return Nothing
		End Function
		'''<summary>
		'''Since the namespace configured for this service reference
		'''in Visual Studio is different from the one indicated in the
		'''server schema, use type-mappers to map between the two.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
			Dim originalNameAttribute As Global.Microsoft.OData.Client.OriginalNameAttribute =
				CType(Global.System.Linq.Enumerable.SingleOrDefault(Global.Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, GetType(Global.Microsoft.OData.Client.OriginalNameAttribute), True)), Global.Microsoft.OData.Client.OriginalNameAttribute)
			If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "ODataDataSource"), Global.System.StringComparison.OrdinalIgnoreCase) Then
				If (Not (originalNameAttribute) Is Nothing) Then
					Return String.Concat("ODataDataSource.", originalNameAttribute.OriginalName)
				End If
				Return String.Concat("ODataDataSource.", clientType.Name)
			End If
			If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "ODataDataSource.Default"), Global.System.StringComparison.OrdinalIgnoreCase) Then
				If (Not (originalNameAttribute) Is Nothing) Then
					Return String.Concat("Default.", originalNameAttribute.OriginalName)
				End If
				Return String.Concat("Default.", clientType.Name)
			End If
			Return Nothing
		End Function
		'''<summary>
		'''There are no comments for Customers in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("Customers")>
		Public ReadOnly Property Customers() As Global.Microsoft.OData.Client.DataServiceQuery(Of ODataDataSource.Customer)
			Get
				If (Me._Customers Is Nothing) Then
					Me._Customers = MyBase.CreateQuery(Of ODataDataSource.Customer)("Customers")
				End If
				Return Me._Customers
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _Customers As Global.Microsoft.OData.Client.DataServiceQuery(Of ODataDataSource.Customer)
		'''<summary>
		'''There are no comments for Movies in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		<Global.Microsoft.OData.Client.OriginalNameAttribute("Movies")>
		Public ReadOnly Property Movies() As Global.Microsoft.OData.Client.DataServiceQuery(Of ODataDataSource.Movie)
			Get
				If (Me._Movies Is Nothing) Then
					Me._Movies = MyBase.CreateQuery(Of ODataDataSource.Movie)("Movies")
				End If
				Return Me._Movies
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private _Movies As Global.Microsoft.OData.Client.DataServiceQuery(Of ODataDataSource.Movie)
		'''<summary>
		'''There are no comments for Customers in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Public Sub AddToCustomers(ByVal customer As ODataDataSource.Customer)
			MyBase.AddObject("Customers", customer)
		End Sub
		'''<summary>
		'''There are no comments for Movies in the schema.
		'''</summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Public Sub AddToMovies(ByVal movie As ODataDataSource.Movie)
			MyBase.AddObject("Movies", movie)
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
		Private MustInherit Class GeneratedEdmModel
			<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
			Private Shared ParsedModel As Global.Microsoft.OData.Edm.IEdmModel = LoadModelFromString()
			<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
			Private Const Edmx As String = "<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">" &
 "  <edmx:DataServices>" &
 "    <Schema Namespace=""ODataDataSource"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">" &
 "      <EntityType Name=""Customer"">" &
 "        <Key>" &
 "          <PropertyRef Name=""CustomerID"" />" &
 "        </Key>" &
 "        <Property Name=""CustomerID"" Type=""Edm.String"" Nullable=""false"" />" &
 "        <Property Name=""CompanyName"" Type=""Edm.String"" />" &
 "        <Property Name=""ContactName"" Type=""Edm.String"" />" &
 "        <Property Name=""Address"" Type=""Edm.String"" />" &
 "      </EntityType>" &
 "      <EntityType Name=""Movie"">" &
 "        <Key>" &
 "          <PropertyRef Name=""ID"" />" &
 "        </Key>" &
 "        <Property Name=""ID"" Type=""Edm.Int32"" Nullable=""false"" />" &
 "        <Property Name=""Title"" Type=""Edm.String"" />" &
 "        <Property Name=""MPAA"" Type=""Edm.String"" />" &
 "        <Property Name=""YearReleased"" Type=""Edm.Int32"" Nullable=""false"" />" &
 "      </EntityType>" &
 "    </Schema>" &
 "    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">" &
 "      <EntityContainer Name=""Container"">" &
 "        <EntitySet Name=""Customers"" EntityType=""ODataDataSource.Customer"" />" &
 "        <EntitySet Name=""Movies"" EntityType=""ODataDataSource.Movie"" />" &
 "      </EntityContainer>" &
 "    </Schema>" &
 "  </edmx:DataServices>" &
 "</edmx:Edmx>"
			<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>
			Public Shared Function GetInstance() As Global.Microsoft.OData.Edm.IEdmModel
                Return ParsedModel
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>  _
            Private Shared Function LoadModelFromString() As Global.Microsoft.OData.Edm.IEdmModel
                Dim reader As Global.System.Xml.XmlReader = CreateXmlReader(Edmx)
                Try
                    Return Global.Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader)
                Finally
                    CType(reader,Global.System.IDisposable).Dispose
                End Try
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.0")>  _
            Private Shared Function CreateXmlReader(ByVal edmxToParse As String) As Global.System.Xml.XmlReader
                Return Global.System.Xml.XmlReader.Create(New Global.System.IO.StringReader(edmxToParse))
            End Function
        End Class
    End Class
End Namespace
