//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapeCity.ActiveReports.Designer.Win {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Designer.Win.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdExport {
            get {
                object obj = ResourceManager.GetObject("CmdExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdNewReport {
            get {
                object obj = ResourceManager.GetObject("CmdNewReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdOpen {
            get {
                object obj = ResourceManager.GetObject("CmdOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdSave {
            get {
                object obj = ResourceManager.GetObject("CmdSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdSaveAs {
            get {
                object obj = ResourceManager.GetObject("CmdSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Selection: .
        /// </summary>
        internal static string CurrentSelection {
            get {
                return ResourceManager.GetString("CurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports 13.
        /// </summary>
        internal static string DefaultGroup {
            get {
                return ResourceManager.GetString("DefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.rdlx.
        /// </summary>
        internal static string DefaultReportNameRdl {
            get {
                return ResourceManager.GetString("DefaultReportNameRdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.rdlx.
        /// </summary>
        internal static string DefaultReportNameRdlx {
            get {
                return ResourceManager.GetString("DefaultReportNameRdlx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.rdlx-master.
        /// </summary>
        internal static string DefaultReportNameRdlxMaster {
            get {
                return ResourceManager.GetString("DefaultReportNameRdlxMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.rpx.
        /// </summary>
        internal static string DefaultReportNameRpx {
            get {
                return ResourceManager.GetString("DefaultReportNameRpx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignerForm.
        /// </summary>
        internal static string DesignerFormName {
            get {
                return ResourceManager.GetString("DesignerFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string DirtySign {
            get {
                return ResourceManager.GetString("DirtySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to &apos;{0}&apos;?.
        /// </summary>
        internal static string EudUnsavedChangesMessage {
            get {
                return ResourceManager.GetString("EudUnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        internal static string EudUnsavedChangesTitle {
            get {
                return ResourceManager.GetString("EudUnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupEditorHide {
            get {
                object obj = ResourceManager.GetObject("GroupEditorHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupEditorShow {
            get {
                object obj = ResourceManager.GetObject("GroupEditorShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Group Editor.
        /// </summary>
        internal static string HideGroupPanelToolTip {
            get {
                return ResourceManager.GetString("HideGroupPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New....
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewToolTip {
            get {
                return ResourceManager.GetString("NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selection.
        /// </summary>
        internal static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open As Library.
        /// </summary>
        internal static string OpenAsLibrary {
            get {
                return ResourceManager.GetString("OpenAsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rdl.
        /// </summary>
        internal static string RdlExtension {
            get {
                return ResourceManager.GetString("RdlExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rdlx.
        /// </summary>
        internal static string RdlxExtension {
            get {
                return ResourceManager.GetString("RdlxExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rdlx-master.
        /// </summary>
        internal static string RdlxMasterExtension {
            get {
                return ResourceManager.GetString("RdlxMasterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is not valid report file..
        /// </summary>
        internal static string ReportIsNotValid {
            get {
                return ResourceManager.GetString("ReportIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rpx.
        /// </summary>
        internal static string RpxExtension {
            get {
                return ResourceManager.GetString("RpxExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndUserDesigner - .
        /// </summary>
        internal static string SampleNameTitle {
            get {
                return ResourceManager.GetString("SampleNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;ave as....
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDL Report Files (*.rdlx)|*.rdlx.
        /// </summary>
        internal static string SaveRdlFilter {
            get {
                return ResourceManager.GetString("SaveRdlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Report Files (*.rdlx)|*.rdlx.
        /// </summary>
        internal static string SaveRdlxFilter {
            get {
                return ResourceManager.GetString("SaveRdlxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDL Report Master Files (*.rdlx-master)|*.rdlx-master.
        /// </summary>
        internal static string SaveRdlxMasterFilter {
            get {
                return ResourceManager.GetString("SaveRdlxMasterFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Report Files (*.rpx)|*.rpx.
        /// </summary>
        internal static string SaveRpxFilter {
            get {
                return ResourceManager.GetString("SaveRpxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Group Editor.
        /// </summary>
        internal static string ShowGroupPanelToolTip {
            get {
                return ResourceManager.GetString("ShowGroupPanelToolTip", resourceCulture);
            }
        }
    }
}
