Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("TestDesignerPro")> 
<Assembly: AssemblyCompany("GrapeCity")> 
<Assembly: AssemblyProduct("TestDesignerPro")> 
<Assembly: AssemblyCopyright("_ArCopyright_")> 
<Assembly: ComVisible(False)>
<Assembly: Guid("a60be3c6-a818-4f8e-be7c-44700be1554c")> 
<Assembly: AssemblyVersion("1.0.0.0")> 
<Assembly: AssemblyFileVersion("1.0.0.0")>
