Imports Microsoft.VisualBasic
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("ReportWizard")>
<Assembly: AssemblyCompany("GrapeCity")>
<Assembly: AssemblyProduct("ReportWizard")>
<Assembly: AssemblyCopyright("_ArCopyright_")>
<Assembly: ComVisible(False)>
<Assembly: Guid("7da81727-d310-4922-a0de-531c29f3c8a1")>
<Assembly: AssemblyVersion("1.0.0.0")>
<Assembly: AssemblyFileVersion("1.0.0.0")>
