//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebService.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JsonDataSource Sample WebService was started successfully.
        /// </summary>
        internal static string bodyOfMessage {
            get {
                return ResourceManager.GetString("bodyOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Customers&quot;:[{&quot;CustomerID&quot;:&quot;1&quot;,&quot;CompanyName&quot;:&quot;喫茶たいむましん&quot;,&quot;ContactName&quot;:&quot;林　 千春&quot;,&quot;ContactTitle&quot;:&quot;店長&quot;,&quot;Address&quot;:&quot;佐賀市長瀬町 23-XX&quot;,&quot;City&quot;:&quot;佐賀市&quot;,&quot;Region&quot;:&quot;&quot;,&quot;PostalCode&quot;:&quot;840-0853&quot;,&quot;Country&quot;:&quot;佐賀県&quot;,&quot;Phone&quot;:&quot;(0952)26-64XX&quot;,&quot;Fax&quot;:&quot;&quot;},{&quot;CustomerID&quot;:&quot;10&quot;,&quot;CompanyName&quot;:&quot;東海道スーパー&quot;,&quot;ContactName&quot;:&quot;河本 なみ&quot;,&quot;ContactTitle&quot;:&quot;料理長&quot;,&quot;Address&quot;:&quot;那覇市繁多川 1-21-XX&quot;,&quot;City&quot;:&quot;那覇市&quot;,&quot;Region&quot;:&quot;&quot;,&quot;PostalCode&quot;:&quot;902-0071&quot;,&quot;Country&quot;:&quot;沖縄県&quot;,&quot;Phone&quot;:&quot;(0988)55-87XX&quot;,&quot;Fax&quot;:&quot;(0988)55-87XX&quot;},{&quot;CustomerID&quot;:&quot;11&quot;,&quot;CompanyName&quot;:&quot;小町ストアー&quot;,&quot;ContactName&quot;:&quot;山久 良美&quot;....
        /// </summary>
        internal static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message : {0}, StackTrace: {1}.
        /// </summary>
        internal static string FormatErrorMessage {
            get {
                return ResourceManager.GetString("FormatErrorMessage", resourceCulture);
            }
        }
    }
}
