//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapeCity.ActiveReports.Samples.Rtf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.Rtf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanGrow.
        /// </summary>
        internal static string PropertyCanGrow {
            get {
                return ResourceManager.GetString("PropertyCanGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether the RtfControl size can increase to accommodate the contents..
        /// </summary>
        internal static string PropertyCanGrowDescription {
            get {
                return ResourceManager.GetString("PropertyCanGrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanShrink.
        /// </summary>
        internal static string PropertyCanShrink {
            get {
                return ResourceManager.GetString("PropertyCanShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether the RtfControl size can decrease to accommodate the contents..
        /// </summary>
        internal static string PropertyCanShrinkDescription {
            get {
                return ResourceManager.GetString("PropertyCanShrinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTF.
        /// </summary>
        internal static string PropertyRtf {
            get {
                return ResourceManager.GetString("PropertyRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTF content editor..
        /// </summary>
        internal static string PropertyRtfDescription {
            get {
                return ResourceManager.GetString("PropertyRtfDescription", resourceCulture);
            }
        }
    }
}
