Imports Microsoft.VisualBasic
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("CustomDataProviderUI")>
<Assembly: AssemblyCompany("GrapeCity")>
<Assembly: AssemblyProduct("CustomDataProviderUI")> 
<Assembly: AssemblyCopyright("_ArCopyright_")> 
<Assembly: ComVisible(False)>
<Assembly: Guid("0b6ceb64-0fc3-445b-8ac8-6fd2a1727a15")>
<Assembly: AssemblyVersion("1.0.0.0")>
<Assembly: AssemblyFileVersion("1.0.0.0")>
