//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapeCity.ActiveReports.Calendar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Calendar.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string AutoLabel {
            get {
                return ResourceManager.GetString("AutoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CalendarAppearance_16 {
            get {
                object obj = ResourceManager.GetObject("CalendarAppearance_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CalendarAppearance_32 {
            get {
                object obj = ResourceManager.GetObject("CalendarAppearance_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Action).
        /// </summary>
        internal static string CalendarAppointmentAction {
            get {
                return ResourceManager.GetString("CalendarAppointmentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to Bookmark.
        /// </summary>
        internal static string CalendarAppointmentBookmark {
            get {
                return ResourceManager.GetString("CalendarAppointmentBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to Report.
        /// </summary>
        internal static string CalendarAppointmentDrillthrough {
            get {
                return ResourceManager.GetString("CalendarAppointmentDrillthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CalendarAppointmentEmptyAction {
            get {
                return ResourceManager.GetString("CalendarAppointmentEmptyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to URL.
        /// </summary>
        internal static string CalendarAppointmentHyperlink {
            get {
                return ResourceManager.GetString("CalendarAppointmentHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalendarDisplayName {
            get {
                return ResourceManager.GetString("CalendarDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar - Calendar Appearance.
        /// </summary>
        internal static string CalendarSmartPanelAppearancePageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelAppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the calendar appearance options..
        /// </summary>
        internal static string CalendarSmartPanelAppearanceSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelAppearanceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Appearance.
        /// </summary>
        internal static string CalendarSmartPanelAppearanceTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Fill Color:.
        /// </summary>
        internal static string CalendarSmartPanelBackgroundFillColorLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelBackgroundFillColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string CalendarSmartPanelBackgroundLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelBackgroundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark ID:.
        /// </summary>
        internal static string CalendarSmartPanelBookmarkIDLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelBookmarkIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Color:.
        /// </summary>
        internal static string CalendarSmartPanelBorderColorLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelBorderColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string CalendarSmartPanelBorderLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelBorderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style:.
        /// </summary>
        internal static string CalendarSmartPanelBorderStyleLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelBorderStyleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        internal static string CalendarSmartPanelBorderWidthLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelBorderWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar - Data Output.
        /// </summary>
        internal static string CalendarSmartPanelDataOutputPageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDataOutputPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set XML data output options..
        /// </summary>
        internal static string CalendarSmartPanelDataOutputSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDataOutputSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataOutput.
        /// </summary>
        internal static string CalendarSmartPanelDataOutputTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDataOutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar - Data.
        /// </summary>
        internal static string CalendarSmartPanelDataPageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDataPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset Name:.
        /// </summary>
        internal static string CalendarSmartPanelDatasetNameLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDatasetNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up data binding on the calendar..
        /// </summary>
        internal static string CalendarSmartPanelDataSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDataSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string CalendarSmartPanelDataTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string CalendarSmartPanelDayAppearancePageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDayAppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set general day appearance options..
        /// </summary>
        internal static string CalendarSmartPanelDayAppearanceSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDayAppearanceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Appearance.
        /// </summary>
        internal static string CalendarSmartPanelDayAppearanceTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDayAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Headers.
        /// </summary>
        internal static string CalendarSmartPanelDayHeadersAppearancePageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDayHeadersAppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set day headers appearance options..
        /// </summary>
        internal static string CalendarSmartPanelDayHeadersAppearanceSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDayHeadersAppearanceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Headers Appearance.
        /// </summary>
        internal static string CalendarSmartPanelDayHeadersAppearanceTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDayHeadersAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar - Detail Grouping.
        /// </summary>
        internal static string CalendarSmartPanelDetailGroupingPageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDetailGroupingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Grouping.
        /// </summary>
        internal static string CalendarSmartPanelDetailGroupingTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDetailGroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document map label:.
        /// </summary>
        internal static string CalendarSmartPanelDocumentMapLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelDocumentMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        internal static string CalendarSmartPanelEndDateLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar - Event Appearance.
        /// </summary>
        internal static string CalendarSmartPanelEventAppearancePageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelEventAppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the appearance of events..
        /// </summary>
        internal static string CalendarSmartPanelEventAppearanceSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelEventAppearanceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Appearance.
        /// </summary>
        internal static string CalendarSmartPanelEventAppearanceTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelEventAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Grouping and Filtering.
        /// </summary>
        internal static string CalendarSmartPanelEventGroupingLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelEventGroupingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Settings.
        /// </summary>
        internal static string CalendarSmartPanelEventSettingsLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelEventSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Color:.
        /// </summary>
        internal static string CalendarSmartPanelFillColorLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFillColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filler Day.
        /// </summary>
        internal static string CalendarSmartPanelFillerDayAppearancePageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFillerDayAppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set filler day appearance options..
        /// </summary>
        internal static string CalendarSmartPanelFillerDayAppearanceSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFillerDayAppearanceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filler Day Appearance.
        /// </summary>
        internal static string CalendarSmartPanelFillerDayAppearanceTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFillerDayAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar - Filters.
        /// </summary>
        internal static string CalendarSmartPanelFiltersPageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFiltersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set record selection conditions.
        /// </summary>
        internal static string CalendarSmartPanelFiltersSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFiltersSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string CalendarSmartPanelFiltersTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFiltersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string CalendarSmartPanelFontColorLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFontColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration:.
        /// </summary>
        internal static string CalendarSmartPanelFontDecorationLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFontDecorationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family:.
        /// </summary>
        internal static string CalendarSmartPanelFontFamilyLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFontFamilyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string CalendarSmartPanelFontLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string CalendarSmartPanelFontSizeLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style:.
        /// </summary>
        internal static string CalendarSmartPanelFontStyleLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFontStyleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        internal static string CalendarSmartPanelFontWeightLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFontWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string CalendarSmartPanelFormatLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        internal static string CalendarSmartPanelFormattingLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelFormattingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar - General.
        /// </summary>
        internal static string CalendarSmartPanelGeneralPageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelGeneralPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set general calendar options.
        /// </summary>
        internal static string CalendarSmartPanelGeneralSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelGeneralSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CalendarSmartPanelGeneralTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalendarSmartPanelHomePageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelHomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string CalendarSmartPanelMonthTitleAppearancePageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelMonthTitleAppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set general month appearance options..
        /// </summary>
        internal static string CalendarSmartPanelMonthTitleAppearanceSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelMonthTitleAppearanceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Appearance.
        /// </summary>
        internal static string CalendarSmartPanelMonthTitleAppearanceTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelMonthTitleAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string CalendarSmartPanelNameLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string CalendarSmartPanelNavigationActionLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNavigationActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to bookmark:.
        /// </summary>
        internal static string CalendarSmartPanelNavigationBookmarkRadioButton {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNavigationBookmarkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to report:.
        /// </summary>
        internal static string CalendarSmartPanelNavigationDrillthroughRadioButton {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNavigationDrillthroughRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to Url:.
        /// </summary>
        internal static string CalendarSmartPanelNavigationHyperlinkRadioButton {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNavigationHyperlinkRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CalendarSmartPanelNavigationNoneRadioButton {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNavigationNoneRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar - Navigation.
        /// </summary>
        internal static string CalendarSmartPanelNavigationPageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNavigationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bookmarks and document map options.
        /// </summary>
        internal static string CalendarSmartPanelNavigationSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNavigationSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string CalendarSmartPanelNavigationTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string CalendarSmartPanelSortingPageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelSortingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the records sort order in the calendar.
        /// </summary>
        internal static string CalendarSmartPanelSortingSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelSortingSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string CalendarSmartPanelSortingTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelSortingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        internal static string CalendarSmartPanelStartDateLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment:.
        /// </summary>
        internal static string CalendarSmartPanelTextAlignLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelTextAlignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip:.
        /// </summary>
        internal static string CalendarSmartPanelTooltipLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelTooltipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string CalendarSmartPanelValueLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Alignment:.
        /// </summary>
        internal static string CalendarSmartPanelVerticalAlignLabel {
            get {
                return ResourceManager.GetString("CalendarSmartPanelVerticalAlignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string CalendarSmartPanelVisibilityPageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelVisibilityPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify visibility options for the calendar.
        /// </summary>
        internal static string CalendarSmartPanelVisibilitySubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelVisibilitySubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string CalendarSmartPanelVisibilityTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelVisibilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string CalendarSmartPanelWeekendAppearancePageTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelWeekendAppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set weekend appearance options..
        /// </summary>
        internal static string CalendarSmartPanelWeekendAppearanceSubTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelWeekendAppearanceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend Appearance.
        /// </summary>
        internal static string CalendarSmartPanelWeekendAppearanceTitle {
            get {
                return ResourceManager.GetString("CalendarSmartPanelWeekendAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComboDown {
            get {
                object obj = ResourceManager.GetObject("ComboDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Custom_16 {
            get {
                object obj = ResourceManager.GetObject("Custom_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Custom_32 {
            get {
                object obj = ResourceManager.GetObject("Custom_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_16 {
            get {
                object obj = ResourceManager.GetObject("Data_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_32 {
            get {
                object obj = ResourceManager.GetObject("Data_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_Output_16 {
            get {
                object obj = ResourceManager.GetObject("Data_Output_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_Output_32 {
            get {
                object obj = ResourceManager.GetObject("Data_Output_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Region:.
        /// </summary>
        internal static string DataRegionCaption {
            get {
                return ResourceManager.GetString("DataRegionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Region &apos;{0}&apos; must specify a dataset..
        /// </summary>
        internal static string DataRegionMustSpecifyDataSet {
            get {
                return ResourceManager.GetString("DataRegionMustSpecifyDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dataset to use for this data region..
        /// </summary>
        internal static string DataSetNamePropertyDescription {
            get {
                return ResourceManager.GetString("DataSetNamePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DayAppearance_16 {
            get {
                object obj = ResourceManager.GetObject("DayAppearance_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DayAppearance_32 {
            get {
                object obj = ResourceManager.GetObject("DayAppearance_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DayHeadersAppearance_16 {
            get {
                object obj = ResourceManager.GetObject("DayHeadersAppearance_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DayHeadersAppearance_32 {
            get {
                object obj = ResourceManager.GetObject("DayHeadersAppearance_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string DirectionColumnHeaderText {
            get {
                return ResourceManager.GetString("DirectionColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name:.
        /// </summary>
        internal static string ElementNameCaption {
            get {
                return ResourceManager.GetString("ElementNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EventAppearance_16 {
            get {
                object obj = ResourceManager.GetObject("EventAppearance_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EventAppearance_32 {
            get {
                object obj = ResourceManager.GetObject("EventAppearance_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string EventCategory {
            get {
                return ResourceManager.GetString("EventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string ExpressionColumnHeaderText {
            get {
                return ResourceManager.GetString("ExpressionColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillerDayAppearance_16 {
            get {
                object obj = ResourceManager.GetObject("FillerDayAppearance_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillerDayAppearance_32 {
            get {
                object obj = ResourceManager.GetObject("FillerDayAppearance_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Filters_16 {
            get {
                object obj = ResourceManager.GetObject("Filters_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Filters_32 {
            get {
                object obj = ResourceManager.GetObject("Filters_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Format_16 {
            get {
                object obj = ResourceManager.GetObject("Format_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Format_32 {
            get {
                object obj = ResourceManager.GetObject("Format_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested DataRegions are not supported within Fixed Page Report..
        /// </summary>
        internal static string FplNestedDataRegions {
            get {
                return ResourceManager.GetString("FplNestedDataRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap General_16 {
            get {
                object obj = ResourceManager.GetObject("General_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap General_32 {
            get {
                object obj = ResourceManager.GetObject("General_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group on:.
        /// </summary>
        internal static string GroupingEditorGroupOnLabel {
            get {
                return ResourceManager.GetString("GroupingEditorGroupOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string GroupingEditorNameLabel {
            get {
                return ResourceManager.GetString("GroupingEditorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageLabel {
            get {
                return ResourceManager.GetString("ImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial visibility:.
        /// </summary>
        internal static string InitialVisibilityCaption {
            get {
                return ResourceManager.GetString("InitialVisibilityCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string InitialVisibilityExpressionLabel {
            get {
                return ResourceManager.GetString("InitialVisibilityExpressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string InitialVisibilityHiddenLabel {
            get {
                return ResourceManager.GetString("InitialVisibilityHiddenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string InitialVisibilityVisibleLabel {
            get {
                return ResourceManager.GetString("InitialVisibilityVisibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataSet name &apos;{0}&apos; is invalid or duplicate. Each DataSet, DataRegion and Grouping requires a unique name..
        /// </summary>
        internal static string InvalidDataSetName {
            get {
                return ResourceManager.GetString("InvalidDataSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Length unit specified..
        /// </summary>
        internal static string InvalidLengthUnit {
            get {
                return ResourceManager.GetString("InvalidLengthUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between &apos;{0}&apos; and &apos;{1},&apos; or the equivalent in cm, mm, pt or pc units..
        /// </summary>
        internal static string InvalidLengthUnitRange {
            get {
                return ResourceManager.GetString("InvalidLengthUnitRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} expression for the {1} &apos;{2}&apos; refers to the global variable PageNumber or TotalPages. These global variables can be used only in the page header and page footer..
        /// </summary>
        internal static string InvalidUsingPageNumberReference {
            get {
                return ResourceManager.GetString("InvalidUsingPageNumberReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string LineColor {
            get {
                return ResourceManager.GetString("LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style:.
        /// </summary>
        internal static string LineStyle {
            get {
                return ResourceManager.GetString("LineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string LineStyleLabel {
            get {
                return ResourceManager.GetString("LineStyleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        internal static string LineWidth {
            get {
                return ResourceManager.GetString("LineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME Type:.
        /// </summary>
        internal static string MimeTypeLabel {
            get {
                return ResourceManager.GetString("MimeTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MonthAppearance_16 {
            get {
                object obj = ResourceManager.GetObject("MonthAppearance_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MonthAppearance_32 {
            get {
                object obj = ResourceManager.GetObject("MonthAppearance_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Navigation_16 {
            get {
                object obj = ResourceManager.GetObject("Navigation_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Navigation_32 {
            get {
                object obj = ResourceManager.GetObject("Navigation_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string OperatorColumnHeaderText {
            get {
                return ResourceManager.GetString("OperatorColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string OutputCaption {
            get {
                return ResourceManager.GetString("OutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixedSize.
        /// </summary>
        internal static string PropertyFixedSize {
            get {
                return ResourceManager.GetString("PropertyFixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the report item for Fixed Page reports..
        /// </summary>
        internal static string PropertyFixedSizeDescription {
            get {
                return ResourceManager.GetString("PropertyFixedSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverflowName.
        /// </summary>
        internal static string PropertyOverflowName {
            get {
                return ResourceManager.GetString("PropertyOverflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Overflow PlaceHolder for Fixed Page reports..
        /// </summary>
        internal static string PropertyOverflowNameDescription {
            get {
                return ResourceManager.GetString("PropertyOverflowNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string PropertySize {
            get {
                return ResourceManager.GetString("PropertySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the report item..
        /// </summary>
        internal static string PropertySizeDescription {
            get {
                return ResourceManager.GetString("PropertySizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sorting_16 {
            get {
                object obj = ResourceManager.GetObject("Sorting_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sorting_32 {
            get {
                object obj = ResourceManager.GetObject("Sorting_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string SourceLabel {
            get {
                return ResourceManager.GetString("SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report item:.
        /// </summary>
        internal static string ToggleItemEditorCaption {
            get {
                return ResourceManager.GetString("ToggleItemEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility can be toggled by another report item.
        /// </summary>
        internal static string ToggleVisibilityCaption {
            get {
                return ResourceManager.GetString("ToggleVisibilityCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Blank&gt;.
        /// </summary>
        internal static string ValueBlank {
            get {
                return ResourceManager.GetString("ValueBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueColumnHeaderText {
            get {
                return ResourceManager.GetString("ValueColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Expression&gt;.
        /// </summary>
        internal static string ValueExpression {
            get {
                return ResourceManager.GetString("ValueExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string ValueTypeLabel {
            get {
                return ResourceManager.GetString("ValueTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Visibility_16 {
            get {
                object obj = ResourceManager.GetObject("Visibility_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Visibility_32 {
            get {
                object obj = ResourceManager.GetObject("Visibility_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WeekendAppearance_16 {
            get {
                object obj = ResourceManager.GetObject("WeekendAppearance_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WeekendAppearance_32 {
            get {
                object obj = ResourceManager.GetObject("WeekendAppearance_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
