//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapeCity.ActiveReports.Samples.SubReport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.SubReport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\Data\Nwind.mdb;Persist Security Info=False.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Sample Report from DropDown List.
        /// </summary>
        internal static string ItemText1 {
            get {
                return ResourceManager.GetString("ItemText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple SubReport.
        /// </summary>
        internal static string ItemText2 {
            get {
                return ResourceManager.GetString("ItemText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested SubReport.
        /// </summary>
        internal static string ItemText3 {
            get {
                return ResourceManager.GetString("ItemText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchical SubReport.
        /// </summary>
        internal static string ItemText4 {
            get {
                return ResourceManager.GetString("ItemText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubReport using the data set that contains relationship.
        /// </summary>
        internal static string ItemText5 {
            get {
                return ResourceManager.GetString("ItemText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master-detail report containing a SubReport.
        /// </summary>
        internal static string ItemText6 {
            get {
                return ResourceManager.GetString("ItemText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark in SubReport.
        /// </summary>
        internal static string ItemText7 {
            get {
                return ResourceManager.GetString("ItemText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a parameter in the SubReport.
        /// </summary>
        internal static string ItemText8 {
            get {
                return ResourceManager.GetString("ItemText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view the DataSet with multiple tables using SubReports.
        /// </summary>
        internal static string ItemText9 {
            get {
                return ResourceManager.GetString("ItemText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptBookmarkMain.rpx.
        /// </summary>
        internal static string rptBookmarkMain {
            get {
                return ResourceManager.GetString("rptBookmarkMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptBookmarkSub.rpx.
        /// </summary>
        internal static string rptBookmarkSub {
            get {
                return ResourceManager.GetString("rptBookmarkSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptDSRelationChildMain.rpx.
        /// </summary>
        internal static string rptDSRelationChildMain {
            get {
                return ResourceManager.GetString("rptDSRelationChildMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptDSRelationChildSub.rpx.
        /// </summary>
        internal static string rptDSRelationChildSub {
            get {
                return ResourceManager.GetString("rptDSRelationChildSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptDSRelationParent.rpx.
        /// </summary>
        internal static string rptDSRelationParent {
            get {
                return ResourceManager.GetString("rptDSRelationParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptHierarchicalMain.rpx.
        /// </summary>
        internal static string rptHierarchicalMain {
            get {
                return ResourceManager.GetString("rptHierarchicalMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptHierarchicalSub.rpx.
        /// </summary>
        internal static string rptHierarchicalSub {
            get {
                return ResourceManager.GetString("rptHierarchicalSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptMasterMain.rpx.
        /// </summary>
        internal static string rptMasterMain {
            get {
                return ResourceManager.GetString("rptMasterMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptMasterSub.rpx.
        /// </summary>
        internal static string rptMasterSub {
            get {
                return ResourceManager.GetString("rptMasterSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptNestedChildMain.rpx.
        /// </summary>
        internal static string rptNestedChildMain {
            get {
                return ResourceManager.GetString("rptNestedChildMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptNestedChildSub.rpx.
        /// </summary>
        internal static string rptNestedChildSub {
            get {
                return ResourceManager.GetString("rptNestedChildSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptNestedParent.rpx.
        /// </summary>
        internal static string rptNestedParent {
            get {
                return ResourceManager.GetString("rptNestedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptParamMain.rpx.
        /// </summary>
        internal static string rptParamMain {
            get {
                return ResourceManager.GetString("rptParamMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptParamSub.rpx.
        /// </summary>
        internal static string rptParamSub {
            get {
                return ResourceManager.GetString("rptParamSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptSimpleMain.rpx.
        /// </summary>
        internal static string rptSimpleMain {
            get {
                return ResourceManager.GetString("rptSimpleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptSimpleSub.rpx.
        /// </summary>
        internal static string rptSimpleSub {
            get {
                return ResourceManager.GetString("rptSimpleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptUnboundDSMain.rpx.
        /// </summary>
        internal static string rptUnboundDSMain {
            get {
                return ResourceManager.GetString("rptUnboundDSMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\rptUnboundDSSub.rpx.
        /// </summary>
        internal static string rptUnboundDSSub {
            get {
                return ResourceManager.GetString("rptUnboundDSSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=MSDataShape;Data Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\Data\Nwind.mdb;Persist Security Info=False.
        /// </summary>
        internal static string ShapeDataConnectionString {
            get {
                return ResourceManager.GetString("ShapeDataConnectionString", resourceCulture);
            }
        }
    }
}
